/* Generated By:JavaCC: Do not edit this line. CompilLab1Constants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilLab1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KW_IF = 10;
  /** RegularExpression Id. */
  int KW_ELSE = 11;
  /** RegularExpression Id. */
  int KW_ELIF = 12;
  /** RegularExpression Id. */
  int KW_FOR = 13;
  /** RegularExpression Id. */
  int KW_WHILE = 14;
  /** RegularExpression Id. */
  int KW_CASE = 15;
  /** RegularExpression Id. */
  int KW_TRY = 16;
  /** RegularExpression Id. */
  int KW_EXCEPT = 17;
  /** RegularExpression Id. */
  int KW_FINALLY = 18;
  /** RegularExpression Id. */
  int KW_RETURN = 19;
  /** RegularExpression Id. */
  int KW_BREAK = 20;
  /** RegularExpression Id. */
  int KW_CONTINUE = 21;
  /** RegularExpression Id. */
  int KW_IMPORT = 22;
  /** RegularExpression Id. */
  int KW_FROM = 23;
  /** RegularExpression Id. */
  int KW_INCLUDE = 24;
  /** RegularExpression Id. */
  int KW_DISCARD = 25;
  /** RegularExpression Id. */
  int KW_RAISE = 26;
  /** RegularExpression Id. */
  int KW_YIELD = 27;
  /** RegularExpression Id. */
  int KW_WHEN = 28;
  /** RegularExpression Id. */
  int KW_OF = 29;
  /** RegularExpression Id. */
  int KW_DO = 30;
  /** RegularExpression Id. */
  int KW_AS = 31;
  /** RegularExpression Id. */
  int KW_IN = 32;
  /** RegularExpression Id. */
  int KW_NOTIN = 33;
  /** RegularExpression Id. */
  int KW_IS = 34;
  /** RegularExpression Id. */
  int KW_ISNOT = 35;
  /** RegularExpression Id. */
  int KW_NIL = 36;
  /** RegularExpression Id. */
  int KW_DEFER = 37;
  /** RegularExpression Id. */
  int KW_USING = 38;
  /** RegularExpression Id. */
  int KW_VAR = 39;
  /** RegularExpression Id. */
  int KW_LET = 40;
  /** RegularExpression Id. */
  int KW_CONST = 41;
  /** RegularExpression Id. */
  int KW_TYPE = 42;
  /** RegularExpression Id. */
  int KW_OBJECT = 43;
  /** RegularExpression Id. */
  int KW_TUPLE = 44;
  /** RegularExpression Id. */
  int KW_ENUM = 45;
  /** RegularExpression Id. */
  int KW_PROC = 46;
  /** RegularExpression Id. */
  int KW_FUNC = 47;
  /** RegularExpression Id. */
  int KW_METHOD = 48;
  /** RegularExpression Id. */
  int KW_ITERATOR = 49;
  /** RegularExpression Id. */
  int KW_TEMPLATE = 50;
  /** RegularExpression Id. */
  int KW_MACRO = 51;
  /** RegularExpression Id. */
  int TYPE_INT = 52;
  /** RegularExpression Id. */
  int TYPE_FLOAT = 53;
  /** RegularExpression Id. */
  int TYPE_STRING = 54;
  /** RegularExpression Id. */
  int TYPE_BOOL = 55;
  /** RegularExpression Id. */
  int OP_PLUS_ASSIGN = 56;
  /** RegularExpression Id. */
  int OP_MINUS_ASSIGN = 57;
  /** RegularExpression Id. */
  int OP_MULTIPLICATION_ASSIGN = 58;
  /** RegularExpression Id. */
  int OP_DIVISION_ASSIGN = 59;
  /** RegularExpression Id. */
  int OP_PLUS = 60;
  /** RegularExpression Id. */
  int OP_MINUS = 61;
  /** RegularExpression Id. */
  int OP_MULTIPLICATION = 62;
  /** RegularExpression Id. */
  int OP_DIVISION = 63;
  /** RegularExpression Id. */
  int OP_MODULUS = 64;
  /** RegularExpression Id. */
  int OP_INT_DIVISION = 65;
  /** RegularExpression Id. */
  int OP_LOGICAL_AND = 66;
  /** RegularExpression Id. */
  int OP_LOGICAL_OR = 67;
  /** RegularExpression Id. */
  int OP_LOGICAL_NOT = 68;
  /** RegularExpression Id. */
  int OP_XOR = 69;
  /** RegularExpression Id. */
  int OP_SHIFT_LEFT = 70;
  /** RegularExpression Id. */
  int OP_SHIFT_RIGHT = 71;
  /** RegularExpression Id. */
  int OP_STRING_CONCATENATION = 72;
  /** RegularExpression Id. */
  int OP_EQUAL = 73;
  /** RegularExpression Id. */
  int OP_NOT_EQUAL = 74;
  /** RegularExpression Id. */
  int OP_LESS_EQUAL = 75;
  /** RegularExpression Id. */
  int OP_GREATER_EQUAL = 76;
  /** RegularExpression Id. */
  int OP_LESS_THAN = 77;
  /** RegularExpression Id. */
  int OP_GREATER_THAN = 78;
  /** RegularExpression Id. */
  int OP_ASSIGN = 79;
  /** RegularExpression Id. */
  int OP_RANGE_EXCLUSIVE = 80;
  /** RegularExpression Id. */
  int OP_RANGE = 81;
  /** RegularExpression Id. */
  int OP_AT_SIGN = 82;
  /** RegularExpression Id. */
  int OP_DEREFERENCE = 83;
  /** RegularExpression Id. */
  int OP_TO_STRING = 84;
  /** RegularExpression Id. */
  int PRAGMA_OPEN = 85;
  /** RegularExpression Id. */
  int PRAGMA_CLOSE = 86;
  /** RegularExpression Id. */
  int BRACKET_DOT_OPEN = 87;
  /** RegularExpression Id. */
  int DOT_BRACKET_CLOSE = 88;
  /** RegularExpression Id. */
  int PAREN_DOT_OPEN = 89;
  /** RegularExpression Id. */
  int DOT_PAREN_CLOSE = 90;
  /** RegularExpression Id. */
  int GENERIC_OPEN = 91;
  /** RegularExpression Id. */
  int DOUBLE_COLON = 92;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 93;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 94;
  /** RegularExpression Id. */
  int LEFT_CURLY_BRACE = 95;
  /** RegularExpression Id. */
  int RIGHT_CURLY_BRACE = 96;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 97;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 98;
  /** RegularExpression Id. */
  int COLON = 99;
  /** RegularExpression Id. */
  int SEMICOLON = 100;
  /** RegularExpression Id. */
  int COMMA = 101;
  /** RegularExpression Id. */
  int DOT = 102;
  /** RegularExpression Id. */
  int NUM_FLOAT = 103;
  /** RegularExpression Id. */
  int NUM_INTEGER_HEXADECIMAL = 104;
  /** RegularExpression Id. */
  int NUM_INTEGER_OCTAL = 105;
  /** RegularExpression Id. */
  int NUM_INTEGER_BINARY = 106;
  /** RegularExpression Id. */
  int NUM_INTEGER = 107;
  /** RegularExpression Id. */
  int STRING_LITERAL = 108;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 109;
  /** RegularExpression Id. */
  int BACKTICK_ID = 110;
  /** RegularExpression Id. */
  int ID = 111;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTILINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"#[\"",
    "\"#[\"",
    "\"]#\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"#\"",
    "\"if\"",
    "\"else\"",
    "\"elif\"",
    "\"for\"",
    "\"while\"",
    "\"case\"",
    "\"try\"",
    "\"except\"",
    "\"finally\"",
    "\"return\"",
    "\"break\"",
    "\"continue\"",
    "\"import\"",
    "\"from\"",
    "\"include\"",
    "\"discard\"",
    "\"raise\"",
    "\"yield\"",
    "\"when\"",
    "\"of\"",
    "\"do\"",
    "\"as\"",
    "\"in\"",
    "\"notin\"",
    "\"is\"",
    "\"isnot\"",
    "\"nil\"",
    "\"defer\"",
    "\"using\"",
    "\"var\"",
    "\"let\"",
    "\"const\"",
    "\"type\"",
    "\"object\"",
    "\"tuple\"",
    "\"enum\"",
    "\"proc\"",
    "\"func\"",
    "\"method\"",
    "\"iterator\"",
    "\"template\"",
    "\"macro\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"bool\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "\"div\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"xor\"",
    "\"shl\"",
    "\"shr\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"..<\"",
    "\"..\"",
    "\"@\"",
    "\"^\"",
    "\"$\"",
    "\"{.\"",
    "\".}\"",
    "\"[.\"",
    "\".]\"",
    "\"(.\"",
    "\".)\"",
    "\"[:\"",
    "\"::\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<NUM_FLOAT>",
    "<NUM_INTEGER_HEXADECIMAL>",
    "<NUM_INTEGER_OCTAL>",
    "<NUM_INTEGER_BINARY>",
    "<NUM_INTEGER>",
    "<STRING_LITERAL>",
    "<CHAR_LITERAL>",
    "<BACKTICK_ID>",
    "<ID>",
  };

}
